# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b022997d2186dd0106e8220bf2b30a820290e0642952c6bd782518c5f353746ddabc896686e3e9d2d030d81e89cedabd51fb935c8034149c7281b32f86a8d1f

test:
  secret_key_base: 50b56047028a86ca32807d934ea21a209dffcab8aa63012e13350b0cef3b61bb93044e9bd1ad6dd89964cfac2897c619085dcf7de5c709eba1d5ae091296ce68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
